package clases;

public enum Mapas {
	SALON_DEAD_DWANG, BOSQUE_ROJO, JARDIN_DEL_JUBILO, PANTANO, DESGUACE, FINCA_MCMILLAN,
	RESIDENCIA_YAMAOKA, RACOON_CITY, ESCUELA_PRIMARIA, HADDONFIELD, SPRINGWOOD, MAPA_ROJO,
	GRANJA_COLWIND, CENTRO_CONMEMORATIVO, JIGSAW, HOSPITAL, ORMOND, ASILO_CROTUS
}
